services:
  kafka:
    image: confluentinc/cp-kafka:7.7.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft sin Zookeeper (1 nodo broker+controller)
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=1
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
<<<<<<< HEAD
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.27.237.31:9092
=======
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.21.42.5:9092
>>>>>>> e2fb1b058ebffa6ae857dcfa09a82595e684b482
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LOG_DIRS=/tmp/kraft-combined-logs
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      # Cluster ID requerido para formatear almacenamiento en KRaft
      - CLUSTER_ID=4L6g3nShT-eMCtK--X86sw
    # Si tu red requiere DNS o IP fija, puedes agregar networks/extra_hosts
    # networks:
    #   - evnet

#networks:
#  evnet:
#    driver: bridge
