@echo off
setlocal
cd /d "%~dp0"
echo Iniciando componentes del Charging Point (PC_B)...
echo.
REM Ventana 1: Build de imagenes y Engine
echo [1/3] Iniciando Build+Engine...
start "Build+Engine" powershell -NoLogo -NoExit -ExecutionPolicy Bypass -File "%~dp0commands_PC_B_build_engine.ps1"
echo Esperando 10 segundos para que Engine este listo...
timeout /t 10 /nobreak >nul
REM Ventana 2: Monitor
echo [2/3] Iniciando Monitor...
start "Monitor" powershell -NoLogo -NoExit -ExecutionPolicy Bypass -File "%~dp0commands_PC_B_monitor.ps1"
echo Esperando 5 segundos...
timeout /t 5 /nobreak >nul
REM Ventana 3: Driver
echo [3/3] Iniciando Driver...
start "Driver" powershell -NoLogo -NoExit -ExecutionPolicy Bypass -File "%~dp0commands_PC_B_driver.ps1"
echo.
echo Todos los componentes han sido iniciados.
echo Presiona cualquier tecla para cerrar esta ventana...
pause >nul
